name: Build and Release Anisette Server

on:
  push:
    tags:
      - 'v*' # Triggers whenever you push a tag like v1.0.0, v2.0, etc.
  workflow_dispatch: # Allows you to trigger the build manually from GitHub Actions tab

permissions:
  contents: write # Grants the workflow permission to create releases and upload assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ca-certificates ldc git clang dub libz-dev libssl-dev

      - name: Build static binary
        run: |
          DC=ldc2 dub build -c "static" --build-mode allAtOnce -b release --compiler=ldc2
          mv anisette-v3-server anisette-v3-server-linux-x86_64

      - name: Create GitHub Release and Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: anisette-v3-server-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
